# Database Configuration (Overrides by Environment Variables: DB_URL, DB_USER, DB_PASSWORD)
db.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/pathology_lab?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
db.driver=com.mysql.cj.jdbc.Driver
db.username=oQHqYYQRoEF96iL.root
db.password=wxJneyy46qOcK0nG

# Email Configuration (Overrides by Environment Variables: EMAIL_FROM, EMAIL_PASSWORD)
email.from=govinddangi5811@gmail.com
email.from.name=PathologyLab
email.reply.to=noreply@pathologylab.com
email.password=jrhcujbnbnkhzdlf
email.smtp.host=smtp.gmail.com
email.smtp.port=587

# File Path Configuration (Overrides by Environment Variable: REPORTS_PATH)
reports.path=/tmp/reports/
